'use client'

import Image from 'next/image'
import Link from 'next/link'
import { signIn } from 'next-auth/react'
import { useRouter, useSearchParams } from 'next/navigation'
import { ArrowLeft, CheckCircle2, LoaderCircle, ShieldCheck } from 'lucide-react'
import { FormEvent, useState } from 'react'

export default function LoginPage() {
  const router = useRouter(); const searchParams = useSearchParams()
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setLoading(true); try { const result = await signIn('credentials', { email, password, redirect: false }); if (result?.error) setError('Email, NIM, atau password belum tepat.'); else { router.push('/dashboard'); router.refresh() } } catch { setError('Terjadi kesalahan. Silakan coba lagi.') } finally { setLoading(false) } }
  return <main className="auth-page"><section className="auth-panel auth-intro"><Link href="/" className="auth-back"><ArrowLeft size={16} /> Kembali ke beranda</Link><div className="auth-intro-content"><span className="auth-logo"><Image src="/assets/logo-udb.png" alt="Logo Universitas Duta Bangsa" width={72} height={72} priority /></span><p className="auth-eyebrow">KAS TI26A3</p><h1>Semua catatan kas, ada di genggaman.</h1><p>Masuk untuk memeriksa tagihan, mengunggah bukti pembayaran, dan mengikuti perkembangan kas kelas.</p><ul><li><CheckCircle2 size={18} /> Tagihan dan riwayat pembayaran</li><li><CheckCircle2 size={18} /> Status verifikasi yang jelas</li><li><CheckCircle2 size={18} /> Informasi kas kelas terkini</li></ul></div></section><section className="auth-form-wrap"><div className="auth-form-card auth-login-card"><div className="auth-mobile-brand"><Image src="/assets/logo-udb.png" alt="" width={38} height={38} /><strong>KAS TI26A3</strong></div><div className="auth-heading"><h2>Selamat datang</h2><p>Masuk untuk melanjutkan ke kas kelasmu.</p></div><form onSubmit={handleSubmit} className="register-form">{searchParams.get('registered') === 'true' && <div className="form-success"><CheckCircle2 size={17} /> Akun berhasil dibuat. Silakan masuk.</div>}{error && <div className="form-alert" role="alert">{error}</div>}<label>Email atau NIM<input type="text" className="input" placeholder="nama@student.udb.ac.id atau NIM" value={email} onChange={(e) => setEmail(e.target.value)} required disabled={loading} autoComplete="username" /></label><label>Password<input type="password" className="input" placeholder="Masukkan password" value={password} onChange={(e) => setPassword(e.target.value)} required disabled={loading} autoComplete="current-password" /></label><button type="submit" className="button button-primary auth-submit" disabled={loading}>{loading ? <><LoaderCircle className="spin" size={17} /> Memeriksa akun...</> : 'Masuk ke dashboard'}</button></form><p className="auth-security"><ShieldCheck size={15} /> Data akun Anda diproses secara aman.</p><p className="auth-switch">Belum punya akun? <Link href="/auth/register">Daftar sekarang</Link></p></div></section></main>
}
